### ISSUE TITLE
Precompiled GPU version does nothing

### ISSUE THREAD

**Issue by Symbai** [HypoX64/DeepMosaics#40]
The non-GPU version works fine. But the precompiled GPU version only shows the black CMD screen for 1 seconds which closes instantly after I click on "run". No error, no log, no result dir.

**Comment by HypoX64** [comment]
Have you installed CUDA? 
If you make sure that. Please open cmd and cd to core, then input deepmosaic, your will see the error.
Like 4:20 in [youtube](https://www.youtube.com/watch?v=1kEmYawJ_vk&t=11s)

**Comment by HypoX64** [comment]
Have you installed CUDA? 
If you make sure that. Please open cmd and cd to core, then input deepmosaic, your will see the error.
Like 4:20 in [youtube](https://www.youtube.com/watch?v=1kEmYawJ_vk&t=11s)

**Comment by Symbai** [comment]
Nvidia-smi:
nvidia-smi
Fri Dec 25 18:49:50 2020
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.79       Driver Version: 460.79       CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce RTX 208... WDDM  | 00000000:0C:00.0  On |                  N/A |
|  0%   41C    P5    49W / 300W |   2627MiB / 11264MiB |     18%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

cmd -> core:
```
Traceback (most recent call last):
  File "deepmosaic.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "C:\ProgramData\Anaconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "cores\core.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "C:\ProgramData\Anaconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "models\runmodel.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "C:\ProgramData\Anaconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "util\data.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "C:\ProgramData\Anaconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "torch\__init__.py", line 127, in <module>
    raise err
OSError: [WinError 126] The specific modul was not found. Error loading "C:\Users\User\Downloads\DeepMosaics_V0.4.0_gpu\core\torch\lib\caffe2_detectron_ops_gpu.dll" or one of its dependencies.
[74232] Failed to execute script deepmosaic
```

**Comment by HypoX64** [comment]
Your Nvidia driver and CUDA version is much newer than me and your problem seems like a widespread problem.
I will try the latest Nvidia driver version later. And there is a sure way to solve all the problem: Install [anaconda](https://www.anaconda.com/) and [pytorch](https://pytorch.org/). By the way, I search for this [question](https://github.com/pytorch/pytorch/issues/35803), it may cause by loss some ".dll".

**Comment by deinlandel** [comment]
Having the same error. 
```
Traceback (most recent call last):
  File "deepmosaic.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "C:\ProgramData\Anaconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "cores\core.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "C:\ProgramData\Anaconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "models\runmodel.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "C:\ProgramData\Anaconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "util\data.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "C:\ProgramData\Anaconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "torch\__init__.py", line 127, in <module>
    err.strerror += f' Error loading "{dll}" or one of its dependencies.'
OSError: [WinError 126] The specified module could not be found. Error loading "U:\Downloads\DeepMosaics_V0.4.0_gpu\core\torch\lib\caffe2_detectron_ops_gpu.dll" or one of its dependencies.
[1332] Failed to execute script deepmosaic
```

When I try to run from Anaconda promt, it gives error too, but another one:
```
Traceback (most recent call last):
  File "deepmosaic.py", line 4, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "cores\core.py", line 6, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "models\runmodel.py", line 6, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "util\data.py", line 4, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "torch\__init__.py", line 335, in <module>

  File "C:\ProgramData\Anaconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "torch\random.py", line 4, in <module>
    from torch._C import default_generator
ImportError: cannot import name 'default_generator' from 'torch._C' (unknown location)
[9716] Failed to execute script deepmosaic
```
