### ISSUE TITLE
v0.4.1 

### ISSUE THREAD

**Issue by shoogamez** [HypoX64/DeepMosaics#47]
[WinError 126] The specified module could not be found. Error loading "C:\DeepMosaics_V0.4.1_gpu\core\torch\lib\caffe2_detectron_ops_gpu.dll" or one of its dependencies.
Please press any key to exit.

how to fix

**Comment by Sherlock-hh** [comment]
Hi, I met the same problem，did you solved this problem? here is my error imfomation:
2021-03-02 14:32:27,239 - DEBUG - Traceback (most recent call last):
  File "../../realsense_openpose/Pymvpose\why.py", line 12, in <module>
    import torch
  File "E:\development\Anaconda3\envs\mvposepy37t1\lib\site-packages\torch\__init__.py", line 116, in <module>
    raise err
OSError: [WinError 127] 找不到指定的程序。 Error loading "E:\development\Anaconda3\envs\mvposepy37t1\lib\site-packages\torch\lib\caffe2_detectron_ops_gpu.dll" or one of its dependencies.

I just use the c++ code to use the python code ,I try python code in cmd with the same evironment  the error dosen't happend

**Comment by Sherlock-hh** [comment]
Hi, I met the same problem，did you solved this problem? here is my error imfomation:
2021-03-02 14:32:27,239 - DEBUG - Traceback (most recent call last):
  File "../../realsense_openpose/Pymvpose\why.py", line 12, in <module>
    import torch
  File "E:\development\Anaconda3\envs\mvposepy37t1\lib\site-packages\torch\__init__.py", line 116, in <module>
    raise err
OSError: [WinError 127] 找不到指定的程序。 Error loading "E:\development\Anaconda3\envs\mvposepy37t1\lib\site-packages\torch\lib\caffe2_detectron_ops_gpu.dll" or one of its dependencies.

I just use the c++ code to use the python code ,I try python code in cmd with the same evironment  the error dosen't happend

**Comment by King9999** [comment]
I'm getting the exact same problem.

**Comment by Sherlock-hh** [comment]
I found my code loaded the dll ：cudnn64_7.dll. prtorch loaded this dll which is from it's own pytorch/....../libs，and after compar, it different from the one my code loaded, just use the dll to instead the one my code used, and the problem solved.
you can check the dll library, compare the diffrence between loaded and in the pytorch/...../libs/

---Original---

**Comment by shoogamez** [comment]
update new

[WinError 126] The specified module could not be found. Error loading "K:\Deepmosaic\DeepMosaics_V0.4.1_gpu\core\torch\lib\caffe2_detectron_ops_gpu.dll" or one of its dependencies.
Please press any key to exit.

**Comment by Nabinamoon** [comment]
Iam having the same problem, anyone resolved it?

Please do share, seems we are left to figure this all out ourselves -_-

**Comment by HypoX64** [comment]
The reason for this bug is very complicated, I need to find a more effective packaging method.
If this kind of error occurs, I suggest not to use GPU version.

**Comment by Milincho** [comment]
Same error here. How can we solve this?

**Comment by Tom-CSTech** [comment]
This appears to still not be fixed even for version 0.5.1... I would've guessed a major version upgrade would've resolved it.

**Comment by Milincho** [comment]
> This appears to still not be fixed even for version 0.5.1... I would've guessed a major version upgrade would've resolved it.

It's a real pity that DeepMosaics became full abandonware. No news for more than 1.5 years and @HypoX64 is not answering any messages, not even to any of his listed email addresses.

**Comment by river371** [comment]
First uninstallation of CUDA and Python and then reinstall the CUDA_11.0.2 version and Python_3.10.6 version. Try it, I can use the GPU version so much, which is more than 10 times faster.

**Comment by Milincho** [comment]
> First uninstallation of CUDA and Python and then reinstall the CUDA_11.0.2 version and Python_3.10.6 version. Try it, I can use the GPU version so much, which is more than 10 times faster.

Nah. 3 years old abandonware...    just doesn't worth the trouble anymore.
